[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  nnoremap <silent> <space>u :call dein#update()<CR>
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'michaeljsmith/vim-indent-object'

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'tpope/vim-bundler'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-eunuch'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nmap <leader>g :Gstatus<CR>
'''

[[plugins]]
repo = 'tpope/vim-projectionist'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-rake'
hook_add = '''
  nnoremap <leader>a :AS<CR>
'''

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-rsi'

[[plugins]]
repo = 'tpope/vim-scriptease'

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'godlygeek/tabular'
hook_add = '''
  inoremap <silent> <Bar>   <Bar><Esc>:call AutoTabularize()<CR>a
'''

[[plugins]]
repo = 'AndrewRadev/linediff.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'thinca/vim-textobj-between'

[[plugins]]
repo = 'rhysd/vim-textobj-anyblock'

[[plugins]]
repo = 'sotte/presenting.vim'

[[plugins]]
repo = 'rizzatti/dash.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
  map + <Plug>(expand_region_expand)
  map - <Plug>(expand_region_shrink)
'''

[[plugins]]
repo = 'SirVer/ultisnips'
if = "has('nvim')"

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'joonty/vdebug'

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <Leader><Leader>s <Plug>(easymotion-s2)
  map <Leader>j <Plug>(easymotion-j)
  map <Leader>k <Plug>(easymotion-k)
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tpope/vim-jdaddy'

[[plugins]]
repo = 'metakirby5/codi.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'nixprime/cpsm'

[[plugins]]
repo = 'bkad/CamelCaseMotion'
hook_add = '''
  call camelcasemotion#CreateMotionMappings('<leader>')
'''

[[plugins]]
repo = 'ludovicchabant/vim-gutentags'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
  autocmd! BufWritePost *.ex Neomake
  autocmd! BufWritePost *.exs Neomake
'''

[[plugins]]
repo = 'dietsche/vim-lastplace'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'briandoll/change-inside-surroundings.vim'

